services:
  mediahost-health:
    image: mediahost/mediahost_health_mcp:latest
    build:
      context: .
      dockerfile: Docker
    container_name: mediahost-health
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./queries.yaml:/app/queries.yaml:ro
    env_file:
      - .env
